In [2]:
import numpy as np

# RECORDING THE ALIGNMENT MATRIX

In [3]:
def editDistDP(str1, str2, m, n):
    
    
    for i in range(m+1):
        for j in range(n+1):
       
            if (i==0 and j==0):
                al[i][j]="N"
   
            elif (i == 0):
                dp[i][j] = j
                al[i][j] = "I"
           
            elif (j == 0):
                dp[i][j] = i    
                al[i][j] = "D"
                
            elif (str1[i-1]==str2[j-1]):
                
                
                inse=dp[i][j-1]+1
                dele=dp[i-1][j]+1
                subs=dp[i-1][j-1]
                
                key_values={'insert':inse,'delete':dele,'subs':subs}
                
                dp[i][j]=min(inse,dele,subs)
                ops=''
                ops=next(key for key, value in key_values.iteritems() if value == dp[i][j])
                
                if(ops=='insert'):
                    al[i][j]='I'
                elif(ops=='delete'):
                    al[i][j]='D'
                else:
                    al[i][j]='S'
                 
            else:
                inse=dp[i][j-1]+1
                dele=dp[i-1][j]+1
                subs=dp[i-1][j-1]+1
                
                key_values={'insert':inse,'delete':dele,'subs':subs}
                
                dp[i][j]=min(inse,dele,subs)    
                ops=''
                ops=next(key for key, value in key_values.iteritems() if value == dp[i][j])
                
                if(ops=='insert'):
                    al[i][j]='I'
                elif(ops=='delete'):
                    al[i][j]='D'
                else:
                    al[i][j]='S'
 
    return dp[i][j]

# FUNCTION FOR PRINTING THE ALIGNMENT

In [4]:
def printAL(mat,str1,str2,m,n):
    
    if(m==0 and n==0):
        return
    
    elif(m==0):
        printAL(mat,str1,str2,m,n-1)
        print( "+" + " ---> " + str2[n-1])
        
    elif(n==0):
        printAL(mat,str1,str2,m-1,n)
        print (str1[m-1]+" <--- "+ "_")

    elif (mat[m][n]=="S"):
        
        printAL(mat,str1,str2,m-1,n-1)
        print (str1[m-1] +" <--> "+str2[n-1])
        
    elif(mat[m][n]=="I"):
        
        printAL(mat,str1,str2,m,n-1)
        print ("+" +" ---> "+ str2[n-1])
        
    else:
        
        printAL(mat,str1,str2,m-1,n)
        print (str1[m-1]+" <--- "+ "_")

In [15]:
str1="accommodation"
str2="intersect"

print len(str1),len(str2)

dp = [[0 for x in range(len(str2)+1)] for x in range(len(str1)+1)]
al=  [[0 for x in range(len(str2)+1)] for x in range(len(str1)+1)]
from datetime import datetime
start_time = datetime.now()
print("EDIT DISTANCE : "+ str(editDistDP(str1, str2, len(str1), len(str2))))
end_time = datetime.now()
print "Time taken for execution",end_time - start_time, "seconds"

13 9
EDIT DISTANCE : 12
Time taken for execution 0:00:00.002000 seconds


In [16]:
print np.matrix(dp)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  1  2  3  4  5  6  7  8  9]
 [ 2  2  2  3  4  5  6  7  7  8]
 [ 3  3  3  3  4  5  6  7  7  8]
 [ 4  4  4  4  4  5  6  7  8  8]
 [ 5  5  5  5  5  5  6  7  8  9]
 [ 6  6  6  6  6  6  6  7  8  9]
 [ 7  7  7  7  7  7  7  7  8  9]
 [ 8  8  8  8  8  8  8  8  8  9]
 [ 9  9  9  9  9  9  9  9  9  9]
 [10 10 10  9 10 10 10 10 10  9]
 [11 10 11 10 10 11 11 11 11 10]
 [12 11 11 11 11 11 12 12 12 11]
 [13 12 11 12 12 12 12 13 13 12]]


In [17]:
print np.matrix(al)

[['N' 'I' 'I' 'I' 'I' 'I' 'I' 'I' 'I' 'I']
 ['D' 'S' 'I' 'I' 'I' 'I' 'I' 'I' 'I' 'I']
 ['D' 'S' 'S' 'I' 'I' 'I' 'I' 'I' 'S' 'I']
 ['D' 'S' 'S' 'S' 'I' 'I' 'I' 'I' 'S' 'I']
 ['D' 'S' 'S' 'S' 'S' 'I' 'I' 'I' 'I' 'S']
 ['D' 'S' 'S' 'S' 'S' 'S' 'I' 'I' 'I' 'I']
 ['D' 'S' 'S' 'S' 'S' 'S' 'S' 'I' 'I' 'I']
 ['D' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'I' 'I']
 ['D' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'I']
 ['D' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S']
 ['D' 'S' 'S' 'S' 'I' 'S' 'S' 'S' 'S' 'S']
 ['D' 'S' 'I' 'D' 'S' 'I' 'S' 'S' 'S' 'D']
 ['D' 'D' 'S' 'D' 'S' 'S' 'I' 'S' 'S' 'D']
 ['D' 'D' 'S' 'I' 'S' 'S' 'S' 'I' 'S' 'D']]


In [18]:
m=len(str1)
n=len(str2)
print (printAL(al,str1,str2,m,n))

a <--- _
c <--> i
c <--> n
o <--> t
m <--> e
m <--> r
o <--> s
d <--> e
a <--> c
t <--> t
i <--- _
o <--- _
n <--- _
None
