In [2]:
import numpy as np

# RECORDING THE ALIGNMENT MATRIX

In [3]:
def editDistDP(str1, str2, m, n):
    
    
    for i in range(m+1):
        for j in range(n+1):
       
            if (i==0 and j==0):
                al[i][j]="N"
   
            elif (i == 0):
                dp[i][j] = j
                al[i][j] = "I"
           
            elif (j == 0):
                dp[i][j] = i    
                al[i][j] = "D"
                
            elif (str1[i-1]==str2[j-1]):
                
                
                inse=dp[i][j-1]+1
                dele=dp[i-1][j]+1
                subs=dp[i-1][j-1]
                
                key_values={'insert':inse,'delete':dele,'subs':subs}
                
                dp[i][j]=min(inse,dele,subs)
                ops=''
                ops=next(key for key, value in key_values.iteritems() if value == dp[i][j])
                
                if(ops=='insert'):
                    al[i][j]='I'
                elif(ops=='delete'):
                    al[i][j]='D'
                else:
                    al[i][j]='S'
                 
            else:
                inse=dp[i][j-1]+1
                dele=dp[i-1][j]+1
                subs=dp[i-1][j-1]+1
                
                key_values={'insert':inse,'delete':dele,'subs':subs}
                
                dp[i][j]=min(inse,dele,subs)    
                ops=''
                ops=next(key for key, value in key_values.iteritems() if value == dp[i][j])
                
                if(ops=='insert'):
                    al[i][j]='I'
                elif(ops=='delete'):
                    al[i][j]='D'
                else:
                    al[i][j]='S'
 
    return dp[i][j]

# FUNCTION FOR PRINTING THE ALIGNMENT

In [7]:
def printAL(mat,str1,str2,m,n):
    
    if(m==0 and n==0):
        return
    
    elif(m==0):
        printAL(mat,str1,str2,m,n-1)
        print( "+" + " ---> " + str2[n-1])
        
    elif(n==0):
        printAL(mat,str1,str2,m-1,n)
        print (str1[m-1]+" <--- "+ "_")

    elif (mat[m][n]=="S"):
        
        printAL(mat,str1,str2,m-1,n-1)
        print (str1[m-1] +" <--> "+str2[n-1])
        
    elif(mat[m][n]=="I"):
        
        printAL(mat,str1,str2,m,n-1)
        print ("+" +" ---> "+ str2[n-1])
        
    else:
        
        printAL(mat,str1,str2,m-1,n)
        print (str1[m-1]+" <--- "+ "_")

In [6]:
str1="accommodation"
str2="anthromoporphization"

print len(str1),len(str2)

dp = [[0 for x in range(len(str2)+1)] for x in range(len(str1)+1)]
al=  [[0 for x in range(len(str2)+1)] for x in range(len(str1)+1)]
from datetime import datetime
start_time = datetime.now()
print("EDIT DISTANCE : "+ str(editDistDP(str1, str2, len(str1), len(str2))))
end_time = datetime.now()
print "Time taken for execution",end_time - start_time, "seconds"

SyntaxError: invalid syntax (<ipython-input-6-6628f407d62d>, line 4)

In [79]:
print np.matrix(dp)

[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 2 2 3 4 5]
 [3 3 3 3 4 5]
 [4 4 4 4 4 5]
 [5 5 5 5 4 5]]


In [80]:
m=len(str1)
n=len(str2)
print (printAL(al,str1,str2,m,n))

m <--- _
a <--> r
n <--> o
v <--> h
i <--> i
+ ---> t
None


In [57]:
d = {'g':a, 'b':b, 't':c}

In [ ]:
minimum=min(d.values())
value_found= next(key for key, value in d.iteritems() if value == minimum)

In [58]:
d

{'b': 5, 'g': 9, 't': 5}